/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CountDownButton: typeof import('./components/UI/CountDownButton/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    EmailForm: typeof import('./components/Login/EmailForm.vue')['default']
    EmailLogin: typeof import('./components/Login/EmailLogin.vue')['default']
    FontAwesomeIcon: typeof import('@fortawesome/vue-fontawesome')['FontAwesomeIcon']
    LoginIndex: typeof import('./components/Login/LoginIndex.vue')['default']
    OAuth: typeof import('./components/Login/OAuth.vue')['default']
    Profile: typeof import('./components/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SupabaseUpload: typeof import('./components/UI/SupabaseUpload/index.vue')['default']
    VerifyOtp: typeof import('./components/Login/VerifyOtp.vue')['default']
  }
}
